services:
  omarchy-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: omarchy-ubuntu-test
    environment:
      - DEBIAN_FRONTEND=noninteractive
    user: testuser
    volumes:
      # Mount the test output directory
      - ./test-results:/test-results
    command: >
      bash -c "
        /home/testuser/.local/share/omarchy/test-install.sh 2>&1 | tee /test-results/test-output.log;
        echo 'Exit code: '$$? >> /test-results/test-output.log
      "